/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'squid' at '10/21/15 5:39 PM' with Gradle 2.6
 *
 * @author squid, @date 10/21/15 5:39 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
