/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'squid' at '10/25/15 3:51 PM' with Gradle 2.7
 *
 * @author squid, @date 10/25/15 3:51 PM
 */
public class BlackdumpServerTest {

}
