
/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'squid' at '10/21/15 5:36 PM' with Gradle 2.6
 *
 * @author squid, @date 10/21/15 5:36 PM
 */
public class EngineTests {

}
